# -*- coding: utf-8 -*-
"""Python_M2_support material02_exercisedavi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KOWxqyI9AaAPfnqOcAPo6k92Mi_0z6PJ

<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Python: Estruturas de Dados
Caderno de **Exercícios**<br> 
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Listas;</li>
  <li>Conjuntos;</li>
  <li>Dicionários.</li>
</ol>

---

# **Exercícios**

## 1\. Listas

Criei uma lista chamada `filmes` com o nome dos 10 primeiros filmes mais bem avaliados no site no [IMDB](https://www.imdb.com/chart/top/). Imprima o resultado.
"""

filmes = ['Um Sonho de Liberdade (1994)', 'O Poderoso Chefão (1972)', 'Batman: O Cavaleiro das Trevas (2008)', 'O Poderoso Chefão II (1974)', '12 Homens e uma Sentença (1957)', 'A Lista de Schindler (1993)', 'O Senhor dos Anéis: O Retorno do Rei (2003)', 'Pulp Fiction: Tempo de Violência (1994)', 'O Senhor dos Anéis: A Sociedade do Anel (2001)', 'Três Homens em Conflito (1966)']
print(filmes)

"""Simule a movimentação do *ranking*. Utilize os métodos `insert` e `pop` para trocar a posição do primeiro e do segundo filme da lista. Imprima o resultado.


"""

filmes.pop(0)
filmes.insert(0, 'O Poderoso Chefão (1972)')
filmes.pop(1)
filmes.insert(1, 'Um Sonho de Liberdade (1994)')

print(filmes)

"""---

## 2\. Conjuntos

Aconteceu um erro no seu *ranking*. Simule a duplicação dos três últimos filmes da lista. Imprima o resultado.
"""

filmes = ['Um Sonho de Liberdade (1994)', 'O Poderoso Chefão (1972)', 'Batman: O Cavaleiro das Trevas (2008)', 'O Poderoso Chefão II (1974)', '12 Homens e uma Sentença (1957)', 'A Lista de Schindler (1993)', 'O Senhor dos Anéis: O Retorno do Rei (2003)', 'Pulp Fiction: Tempo de Violência (1994)', 'O Senhor dos Anéis: A Sociedade do Anel (2001)', 'Três Homens em Conflito (1966)', 'Pulp Fiction: Tempo de Violência (1994)', 'O Senhor dos Anéis: A Sociedade do Anel (2001)', 'Três Homens em Conflito (1966)']
print(filmes)

"""Utiliza a conversão `set` e `list` para remover os valores duplicados. Imprima o resultado. """

filmes = set(filmes)
print(filmes)

"""---

## 3\. Dicionários

Repita os exercícios da parte 1 (listas). Os elementos da lista `filmes` devem ser dicionários no seguinte formato: `{'nome': <nome-do-filme>, 'ano': <ano do filme>}, 'sinopse': <sinopse do filme>}`.
"""

filmes1 = {'nome' : 'Um Sonho de Liberdade',  
            'ano' : 1994, 
            'sinopse': 'Dois homens presos se reúnem ao longo de vários anos, encontrando consolo e eventual redenção através de atos de decência comum.',
}

filmes2 = {'nome' : 'O Poderoso Chefão',
           'ano' : 1972,
            'sinopse' : 'O patriarca idoso de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante.',       
}

filmes3 = {'nome' : 'Batman: O Cavaleiro das Trevas', 
            'ano': 2008, 
            'sinopse' : 'Quando a ameaça conhecida como O Coringa surge de seu passado, causa estragos e caos nas pessoas de Gotham. O Cavaleiro das Trevas deve aceitar um dos maiores testes para combater a injustiça.',           
}

filmes4 = {'nome' : 'O Poderoso Chefão II',
            'ano' : 1974,
            'sinopse' : 'Em 1950, Michael Corleone, agora à frente da família, tenta expandir o negócio do crime a Las Vegas, Los Angeles e Cuba. Paralelamente, é revelada a história de Vito Corleone, e de como saiu da Sicília e chegou a Nova Iorque.',          
}

filmes5 = {'nome' : '12 Homens e uma Sentença',
            'ano' : 1957,
            'sinopse' : 'Um jurado que se aposenta tenta evitar um erro judicial forçando seus colegas a reconsiderarem as evidências.',
}

filmes6 = {'nome' : 'A Lista de Schindler',
            'ano' : 1993,
            'sinopse' : 'Depois de testemunhar a perseguição dos judaicos na Polônia ocupada pelos alemães durante a Segunda Guerra Mundial, o industrial Oskar Schindler se começa a preocupar com sua força de trabalho judaica.',
}

filmes7 = {'nome' : 'O Senhor dos Anéis: O Retorno do Rei',
            'ano' : 2003, 
            'sinopse' : 'Gandalf e Aragorn lideram o Mundo dos Homens contra o exército de Sauron para desviar o olhar de Frodo e Sam quando eles se aproximam á Montanha da Perdição com o Um Anel.',          
}

filmes8 = {'nome' : 'Pulp Fiction: Tempo de Violência',
            'ano' : 1994, 
            'sinopse' : 'As vidas de dois assassinos da máfia, um boxeador, um gângster e sua esposa, e um par de bandidos se entrelaçam em quatro histórias de violência e redenção.',         
}

filmes9 =  {'nome' : 'O Senhor dos Anéis: A Sociedade do Anel',
            'ano' : 2001,
            'sinopse' : 'Um manso hobbit do Condado e oito companheiros partem em uma jornada para destruir o poderoso Um Anel e salvar a Terra-média das Trevas.',          
}          
filmes10 = {'nome' : 'Três Homens em Conflito',
            'ano' : 1966,
            'sinopse' : 'Um impostor se junta com dois homens para encontrar fortuna num remoto cemitério.'
}

print(filmes1)
print(filmes2)
print(filmes3)
print(filmes4)
print(filmes5)
print(filmes6)
print(filmes7)
print(filmes8)
print(filmes9)
print(filmes10)

filmes_list = [filmes1, filmes2, filmes3, filmes4, filmes5, filmes6, filmes7, filmes8, filmes9, filmes10]
print(filmes_list)